### ISSUE TITLE
translation doesn't work

### ISSUE THREAD

**Issue by user2358747** [Joel2B/Auto-Translate-Youtube-Subtitles#1]

**Comment by Joel2B** [comment]
to make the translation work, you have to put the [translation-api](https://github.com/Joel2B/Auto-Translate-Youtube-Subtitles/tree/main/src/translation-api) folder inside a web server running php.
for example if you use xampp put it inside the htdocs folder and paste the url of the folder inside webpack.config.js
replaces -> http://localhost/chrome-extensions/custom-subtitles/dist/translation-api/
by your own url -> http://localhost/translation-api/
or you can use this one to try -> https://appsdev.cyou/translation-api/

**Comment by jasonblack1027** [comment]
Hi, I installed MAMP and put the folder: translation-api at http://localhost/chrome-extensions/custom-subtitles/dist/translation-api/, 
but it seems that the extension does not work as a translator. 
Please tell me what to do? 
Thank you so much.
